---
# If you want to explicitly define an interface that ALL control nodes
# should use to propagate the VIP, define it here. Otherwise, kube-vip
# will determine the right interface automatically at runtime.
kube_vip_iface: null

# Log Level to be used: 1 (lowest) to 5 (most verbose). 4 is default.
# Reference: https://kube-vip.io/docs/installation/flags/#environment-variables under Troubleshooting
kube_vip_loglevel: 4
# Same, but for cloud provider
kube_vip_cloud_provider_loglevel: 4

# Forward Method to use for kube-vip
# Reference: https://kube-vip.io/docs/installation/flags/#environment-variables under VIP Config/lb_fwdmethod
kube_vip_fwdmethod: local

# Use Kube-VIP to elect leaders per service.
# Reference: https://kube-vip.io/docs/installation/flags/#environment-variables under VIP Config/svc_election
kube_vip_svc_election: true

# Name of the master group
group_name_master: master

# yamllint disable rule:line-length
server_init_args: >-
  {% if groups[group_name_master | default('master')] | length > 1 %}
    {% if ansible_hostname == hostvars[groups[group_name_master | default('master')][0]]['ansible_hostname'] %}
      --cluster-init
    {% else %}
      --server https://{{ hostvars[groups[group_name_master | default('master')][0]].k3s_node_ip | split(",") | first | ansible.utils.ipwrap }}:6443
    {% endif %}
    --token {{ k3s_token }}
  {% endif %}
  {{ extra_server_args | default('') }}
