---
- name: Create manifests directory on first master
  file:
    path: /var/lib/rancher/k3s/server/manifests
    state: directory
    owner: root
    group: root
    mode: 0644
  when: ansible_hostname == hostvars[groups[group_name_master | default('master')][0]]['ansible_hostname']

- name: Download vip cloud provider manifest to first master
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/kube-vip/kube-vip-cloud-provider/{{ kube_vip_cloud_provider_tag_version | default('main') }}/manifest/kube-vip-cloud-controller.yaml"  # noqa yaml[line-length]
    dest: "/var/lib/rancher/k3s/server/manifests/kube-vip-cloud-controller.yaml"
    owner: root
    group: root
    mode: 0644
  when: ansible_hostname == hostvars[groups[group_name_master | default('master')][0]]['ansible_hostname']

- name: Modify vip controller's commandline to add logging
  command:
    argv:
      - /usr/bin/env
      - yq
      - -i
      - eval
      # TODO Using document_index might not be the best idea. Some kind of filtering by kind=DaemonSet would be cleaner.
      - select( di == 3 ).spec.template.spec.containers[0].command |= . + ["-v","{{ kube_vip_loglevel }}"]
      - "/var/lib/rancher/k3s/server/manifests/kube-vip-cloud-controller.yaml"
  when:
    - kube_vip_cloud_provider_loglevel != 4 # default = 4
    - ansible_hostname == hostvars[groups[group_name_master | default('master')][0]]['ansible_hostname']

- name: Copy kubevip configMap manifest to first master
  template:
    src: "kubevip.yaml.j2"
    dest: "/var/lib/rancher/k3s/server/manifests/kubevip.yaml"
    owner: root
    group: root
    mode: 0644
  when: ansible_hostname == hostvars[groups[group_name_master | default('master')][0]]['ansible_hostname']
